# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.4.2"

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run Pyinstaller
      run: |
        source .venv/bin/activate
        pyinstaller -c -p ./ -F bcgrun.py

    - uses: actions/upload-artifact@v3
      with:
        name: bcgrun-${{ matrix.os }}
        path: dist/*
